export const stateOptions = {AF : ['Badakhshan','Badghis','Baghlan','Balkh','Bamyan','Daykundi','Farah','Faryab','Ghazni','Ghor','Helmand','Herat','Jowzjan','Kabul','Kandahar','Kapisa','Khost','Kunar','Kunduz','Laghman','Logar','Nangarhar','Nimroz','Nuristan','Paktia','Paktika','Panjshir','Parwan','Samangan','Sar-e Pol','Takhar','Urozgan','Wardak','Zabul'],  AX : ['Mariehamn', 'Jomala', 'Finström', 'Sund', 'Lemland', 'Saltvik', 'Hammarland', 'Eckerö', 'Föglö', 'Geta', 'Brändö', 'Kumlinge', 'Vårdö'],
    AL : ['Berat', 'Dibër', 'Durrës', 'Elbasan', 'Fier', 'Gjirokastër', 'Korçë', 'Kukës', 'Lezhë', 'Shkodër', 'Tiranë', 'Vlorë'],
    DZ : ['Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouira', 'Tamanrasset', 'Tébessa','Tlemcen', 'Tiaret', 'Tizi Ouzou', 'Alger', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda', 'Sidi Bel Abbès', 'Annaba', 'Guelma','Constantine', 'Médéa', 'Mostaganem', 'M-Sila', 'Mascara', 'Ouargla', 'Oran', 'El Bayadh', 'Illizi', 'Bordj Bou Arréridj','Boumerdès', 'El Tarf', 'Tindouf', 'Tissemsilt', 'El Oued', 'Khenchela', 'Souk Ahras', 'Tipaza', 'Mila', 'Aïn Defla', 'Naâma','Aïn Témouchent', 'Ghardaïa', 'Relizane'],
    AS : ['Eastern District', 'Manu‘a District', 'Rose Island', 'Swains Island', 'Western District'],
    Ad : ['Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino', 'Sant Julià de Lòria'],
    AO : ['Bengo', 'Benguela', 'Bié', 'Cabinda', 'Cunene', 'Huambo', 'Huíla', 'Kuando Kubango', 'Kwanza Norte', 'Kwanza Sul', 'Luanda','Lunda Norte', 'Lunda Sul', 'Malanje', 'Moxico', 'Namibe', 'Uíge', 'Zaire'],
    AI : ['Anguilla'],
    AQ : ['Antarctica'],
    AG : ['Saint George', 'Saint John', 'Saint Mary', 'Saint Paul', 'Saint Peter', 'Saint Philip'],
    AR : ['Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja','Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego','Tucumán'],
    AM : ['Aragatsotn', 'Ararat', 'Armavir', 'Gegharkunik', 'Kotayk', 'Lori', 'Shirak', 'Syunik', 'Tavush', 'Vayots Dzor', 'Yerevan'],
    AW : ['Noord', 'Oranjestad', 'Paradera', 'San Nicolas', 'Santa Cruz', 'Savaneta'],
    AU : ['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania'],
    US : ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware','Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky','Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico','New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania','Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont','Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
    IN : [{ "name": "Andaman and Nicobar Islands", "code": "AN"},
    {"name": "Andhra Pradesh","code": "AP"},
{"name": "Arunachal Pradesh","code": "AR"},
{"name": "Assam","code": "AS"},
{"name": "Bihar","code": "BR"},
{"name": "Chandigarh","code": "CH"},
{"name": "Chhattisgarh","code": "CT"},
{"name": "Dadra and Nagar Haveli and Daman and Diu","code": "DH"},
{"name": "Delhi","code": "DL"},
{"name": "Goa", "code": "GA"},
{"name": "Gujarat","code": "GJ"},
{"name": "Haryana","code": "HR"},
{"name": "Himachal Pradesh","code": "HP"},
{"name": "Jammu and Kashmir","code": "JK"},
{"name": "Jharkhand","code": "JH"},
{"name": "Karnataka","code": "KA"},
{"name": "Kerala", "code": "KL"},
{"name": "Ladakh","code": "LA"},
{"name": "Lakshadweep","code": "LD"},
{"name": "Madhya Pradesh","code": "MP"},
{"name": "Maharashtra","code": "MH"},
{"name": "Manipur","code": "MN"},
{"name": "Meghalaya","code": "ML"},
{"name": "Mizoram","code": "MZ"},
{"name": "Nagaland","code": "NL"},
{"name": "Odisha","code": "OR"},
{"name": "Puducherry","code": "PY"},
{"name": "Punjab","code": "PB"},
{"name": "Rajasthan","code": "RJ"},
{"name": "Sikkim","code": "SK"},
{"name": "Tamil Nadu","code": "TN"},
{"name": "Telangana","code": "TG"},
{"name": "Tripura","code": "TR"},
{"name": "Uttar Pradesh","code": "UP"},
{"name": "Uttarakhand","code": "UK"},
{"name": "West Bengal","code": "WB"}],
};


export const districtOption = {
    Telangana :[{ "State_Code": "TG", "District_Key": "TG_Adilabad", "District": "Adilabad" },
      { "State_Code": "TG","District_Key": "TG_Bhadradri Kothagudem", "District": "Bhadradri Kothagudem"      },
      { "State_Code": "TG", "District_Key": "TG_Hyderabad", "District": "Hyderabad"      },
      { "State_Code": "TG", "District_Key": "TG_Jagtial", "District": "Jagtial"  },
      {"State_Code": "TG", "District_Key": "TG_Jangaon", "District": "Jangaon"      },
      { "State_Code": "TG", "District_Key": "TG_Jayashankar Bhupalapally", "District": "Jayashankar Bhupalapally"      },
      { "State_Code": "TG", "District_Key": "TG_Jogulamba Gadwal", "District": "Jogulamba Gadwal"      },
      { "State_Code": "TG", "District_Key": "TG_Kamareddy", "District": "Kamareddy"      },
      { "State_Code": "TG", "District_Key": "TG_Karimnagar", "District": "Karimnagar"      },
      {"State_Code": "TG", "District_Key": "TG_Khammam", "District": "Khammam"},
      { "State_Code": "TG", "District_Key": "TG_Komaram Bheem", "District": "Komaram Bheem"},
      { "State_Code": "TG", "District_Key": "TG_Mahabubabad", "District": "Mahabubabad"},
      { "State_Code": "TG", "District_Key": "TG_Mahabubnagar", "District": "Mahabubnagar"},
      { "State_Code": "TG", "District_Key": "TG_Mancherial", "District": "Mancherial" },
      { "State_Code": "TG", "District_Key": "TG_Medak", "District": "Medak" },
      { "State_Code": "TG", "District_Key": "TG_Medchal Malkajgiri", "District": "Medchal Malkajgiri"},
      { "State_Code": "TG", "District_Key": "TG_Mulugu", "District": "Mulugu"},
      { "State_Code": "TG", "District_Key": "TG_Nagarkurnool", "District": "Nagarkurnool"},
      { "State_Code": "TG","District_Key": "TG_Nalgonda","District": "Nalgonda"},
      { "State_Code": "TG", "District_Key": "TG_Narayanpet", "District": "Narayanpet" },
      { "State_Code": "TG", "District_Key": "TG_Nirmal", "District": "Nirmal"},
      {"State_Code": "TG", "District_Key": "TG_Nizamabad","District": "Nizamabad" },
      { "State_Code": "TG", "District_Key": "TG_Peddapalli", "District": "Peddapalli" },
      { "State_Code": "TG", "District_Key": "TG_Rajanna Sircilla", "District": "Rajanna Sircilla" },
      { "State_Code": "TG", "District_Key": "TG_Ranga Reddy", "District": "Ranga Reddy" },
      { "State_Code": "TG", "District_Key": "TG_Sangareddy", "District": "Sangareddy"},
      {"State_Code": "TG","District_Key": "TG_Siddipet","District": "Siddipet"},
      {"State_Code": "TG", "District_Key": "TG_Suryapet", "District": "Suryapet"},
      { "State_Code": "TG", "District_Key": "TG_Vikarabad","District": "Vikarabad" },
      { "State_Code": "TG","District_Key": "TG_Wanaparthy", "District": "Wanaparthy" },
      { "State_Code": "TG", "District_Key": "TG_Warangal Rural","District": "Warangal Rural"},
      { "State_Code": "TG", "District_Key": "TG_Warangal Urban","District": "Warangal Urban" },
      {"State_Code": "TG","District_Key": "TG_Yadadri Bhuvanagiri","District": "Yadadri Bhuvanagiri" },]
     };


export const mandalOption = {
      
}